export const GAME_MODERN_PLATFORMS = [
  { text: 'AirConsole', value: 389 },
  { text: 'Amazon Fire TV', value: 132 },
  { text: 'Android', value: 34 },
  { text: 'Arduboy', value: 438 },
  { text: 'Evercade', value: 309 },
  { text: 'Gear VR', value: 388 },
  { text: 'iOS', value: 39 },
  { text: 'Linux', value: 3 },
  { text: 'Mac', value: 14 },
  { text: 'Meta Quest 2', value: 386 },
  { text: 'Meta Quest 3', value: 471 },
  { text: 'Nintendo Switch', value: 130 },
  { text: 'Nintendo Switch 2', value: 508 },
  { text: 'Oculus Go', value: 387 },
  { text: 'Oculus Quest', value: 384 },
  { text: 'Oculus Rift', value: 385 },
  { text: 'Oculus VR', value: 162 },
  { text: 'PC (Microsoft Windows)', value: 6 },
  { text: 'PlayStation 4', value: 48 },
  { text: 'PlayStation 5', value: 167 },
  { text: 'PlayStation VR', value: 165 },
  { text: 'PlayStation VR2', value: 390 },
  { text: 'Playdate', value: 381 },
  { text: 'Polymega', value: 509 },
  { text: 'SteamVR', value: 163 },
  { text: 'Web browser', value: 82 },
  { text: 'Windows Mixed Reality', value: 161 },
  { text: 'Xbox One', value: 49 },
  { text: 'Xbox Series X|S', value: 169 },
  { text: 'visionOS', value: 472 },
]

export const GAME_LEGACY_PLATFORMS = [
  { text: '64DD', value: 416 },
  { text: 'Advanced Pico Beena', value: 507 },
  { text: 'BlackBerry OS', value: 73 },
  { text: 'Digiblast', value: 486 },
  { text: 'Dreamcast', value: 23 },
  { text: 'Game Boy', value: 33 },
  { text: 'Game Boy Advance', value: 24 },
  { text: 'Game Boy Color', value: 22 },
  { text: 'Gizmondo', value: 474 },
  { text: 'Google Stadia', value: 170 },
  { text: 'HyperScan', value: 407 },
  { text: 'Intellivision Amico', value: 382 },
  { text: 'Leapster Explorer/LeadPad Explorer', value: 413 },
  { text: 'N-Gage', value: 42 },
  { text: 'New Nintendo 3DS', value: 137 },
  { text: 'Nintendo 3DS', value: 37 },
  { text: 'Nintendo 64', value: 4 },
  { text: 'Nintendo DS', value: 20 },
  { text: 'Nintendo DSi', value: 159 },
  { text: 'Nintendo GameCube', value: 21 },
  { text: 'Nuon', value: 122 },
  { text: 'OnLive Game System', value: 113 },
  { text: 'Ouya', value: 72 },
  { text: 'Palm OS', value: 417 },
  { text: 'Panasonic Jungle', value: 477 },
  { text: 'PlayStation', value: 7 },
  { text: 'PlayStation 2', value: 8 },
  { text: 'PlayStation 3', value: 9 },
  { text: 'PlayStation Portable', value: 38 },
  { text: 'PlayStation Vita', value: 46 },
  { text: 'Pokémon mini', value: 166 },
  { text: 'Tapwave Zodiac', value: 44 },
  { text: 'Virtual Boy', value: 87 },
  { text: 'Virtual Console', value: 47 },
  { text: 'Windows Mobile', value: 405 },
  { text: 'Windows Phone', value: 74 },
  { text: 'Wii', value: 5 },
  { text: 'Wii U', value: 41 },
  { text: 'WonderSwan', value: 57 },
  { text: 'WonderSwan Color', value: 123 },
  { text: 'Xbox', value: 11 },
  { text: 'Xbox 360', value: 12 },
  { text: 'Zeebo', value: 240 },
]

const GAME_RETRO_PLATFORMS = [
  { text: '1292 Advanced Programmable Video System', value: 139 },
  { text: '3DO Interactive Multiplayer', value: 50 },
  { text: 'Acorn Archimedes', value: 116 },
  { text: 'Acorn Electron', value: 134 },
  { text: 'Amiga', value: 16 },
  { text: 'Amiga CD32', value: 114 },
  { text: 'Amstrad CPC', value: 25 },
  { text: 'Amstrad GX4000', value: 506 },
  { text: 'Arcade', value: 52 },
  { text: 'Arcadia 2001', value: 473 },
  { text: 'Apple II', value: 75 },
  { text: 'Apple IIGS', value: 115 },
  { text: 'Apple Pippin', value: 476 },
  { text: 'Atari 2600', value: 59 },
  { text: 'Atari 5200', value: 66 },
  { text: 'Atari 7800', value: 60 },
  { text: 'Atari 8-bit', value: 65 },
  { text: 'Atari Jaguar', value: 62 },
  { text: 'Atari Jaguar CD', value: 410 },
  { text: 'Atari ST/STE', value: 63 },
  { text: 'AY-3-8500', value: 140 },
  { text: 'AY-3-8603', value: 145 },
  { text: 'AY-3-8605', value: 146 },
  { text: 'AY-3-8606', value: 147 },
  { text: 'AY-3-8607', value: 148 },
  { text: 'AY-3-8610', value: 141 },
  { text: 'AY-3-8710', value: 144 },
  { text: 'Bally Astrocade', value: 91 },
  { text: 'BBC Microcomputer System', value: 69 },
  { text: 'Blu-ray Player', value: 239 },
  { text: 'CDC Cyber 70', value: 109 },
  { text: 'Casio Loopy', value: 380 },
  { text: 'ColecoVision', value: 68 },
  { text: 'Commodore 16', value: 93 },
  { text: 'Commodore C64/128/MAX', value: 15 },
  { text: 'Commodore CDTV', value: 158 },
  { text: 'Commodore PET', value: 90 },
  { text: 'Commodore Plus/4', value: 94 },
  { text: 'DEC GT40', value: 98 },
  { text: 'DOS', value: 13 },
  { text: 'DVD Player', value: 238 },
  { text: 'Dragon 32/64', value: 153 },
  { text: 'EDSAC', value: 102 },
  { text: 'Elektor TV Games Computer', value: 505 },
  { text: 'Epoch Cassette Vision', value: 375 },
  { text: 'Epoch Super Cassette Vision', value: 376 },
  { text: 'Exidy Sorcerer', value: 236 },
  { text: 'Family Computer', value: 99 },
  { text: 'Family Computer Disk System', value: 51 },
  { text: 'Fairchild Channel F', value: 127 },
  { text: 'Ferranti Nimrod Computer', value: 101 },
  { text: 'FM Towns', value: 118 },
  { text: 'FM-7', value: 152 },
  { text: 'Game & Watch', value: 307 },
  { text: 'Game Boy', value: 33 },
  { text: 'Gamate', value: 378 },
  { text: 'Game.com', value: 379 },
  { text: 'HP 2100', value: 104 },
  { text: 'HP 3000', value: 105 },
  { text: 'Handheld Electronic LCD', value: 411 },
  { text: 'Hyper Neo Geo 64', value: 135 },
  { text: 'Imlac PDS-1', value: 111 },
  { text: 'Intellivision', value: 67 },
  { text: 'LaserActive', value: 487 },
  { text: 'Legacy Computer', value: 409 },
  { text: 'MSX', value: 27 },
  { text: 'MSX2', value: 53 },
  { text: 'Mega Duck/Cougar Boy', value: 408 },
  { text: 'Microcomputer', value: 112 },
  { text: 'Microvision', value: 89 },
  { text: 'Neo Geo AES', value: 80 },
  { text: 'Neo Geo CD', value: 136 },
  { text: 'Neo Geo MVS', value: 79 },
  { text: 'Neo Geo Pocket', value: 119 },
  { text: 'Neo Geo Pocket Color', value: 120 },
  { text: 'NEC PC-6000 Series', value: 157 },
  { text: 'Nintendo Entertainment System', value: 18 },
  { text: 'Nintendo GameCube', value: 21 },
  { text: 'Odyssey', value: 88 },
  { text: 'Odyssey 2 / Videopac G7000', value: 133 },
  { text: 'OOParts', value: 372 },
  { text: 'PC (Microsoft Windows)', value: 6 },
  { text: 'PC Engine SuperGrafx', value: 128 },
  { text: 'PC-FX', value: 274 },
  { text: 'PC-50X Family', value: 142 },
  { text: 'PC-8800 Series', value: 125 },
  { text: 'PC-9800 Series', value: 149 },
  { text: 'PDP-1', value: 95 },
  { text: 'PDP-10', value: 96 },
  { text: 'PDP-11', value: 108 },
  { text: 'PDP-7', value: 103 },
  { text: 'PDP-8', value: 97 },
  { text: 'Philips CD-i', value: 117 },
  { text: 'Pocke tStation', value: 441 },
  { text: 'Plug & Play', value: 377 },
  { text: 'R-Zone', value: 475 },
  { text: 'Satellaview', value: 306 },
  { text: 'SDS Sigma 7', value: 106 },
  { text: 'Sega 32X', value: 30 },
  { text: 'Sega CD', value: 78 },
  { text: 'Sega CD 32X', value: 482 },
  { text: 'Sega Game Gear', value: 35 },
  { text: 'Sega Master System/Mark III', value: 64 },
  { text: 'Sega Mega Drive/Genesis', value: 29 },
  { text: 'Sega Pico', value: 339 },
  { text: 'Sega Saturn', value: 32 },
  { text: 'SG-1000', value: 84 },
  { text: 'Sharp MZ-2200', value: 374 },
  { text: 'Sharp X1', value: 77 },
  { text: 'Sharp X68000', value: 121 },
  { text: 'Sinclair QL', value: 406 },
  { text: 'Sinclair ZX81', value: 373 },
  { text: 'Sol-20', value: 237 },
  { text: "Super A'Can", value: 480 },
  { text: 'Super NES CD-ROM System', value: 131 },
  { text: 'Super Nintendo Entertainment System', value: 19 },
  { text: 'SwanCrystal', value: 124 },
  { text: 'Tatung Einstein', value: 155 },
  { text: "Terebikko / See 'n Say Video Phone", value: 479 },
  { text: 'Texas Instruments TI-99', value: 129 },
  { text: 'Thomson MO5', value: 156 },
  { text: 'Tomy Tutor / Pyuta / Grandstand Tutor', value: 481 },
  { text: 'TRS-80', value: 126 },
  { text: 'TRS-80 Color Computer', value: 151 },
  { text: 'TurboGrafx-16/PC Engine', value: 86 },
  { text: 'Turbografx-16/PC Engine CD', value: 150 },
  { text: 'Uzebox', value: 504 },
  { text: 'V.Smile', value: 439 },
  { text: 'VC 4000', value: 138 },
  { text: 'Vectrex', value: 70 },
  { text: 'Visual Memory Unit / Visual Memory System', value: 440 },
  { text: 'Watara/QuickShot Supervision', value: 415 },
  { text: 'ZX Spectrum', value: 26 },
]
