export const GENRES = [
  { text: 'Point-and-click', value: 2 },
  { text: 'Fighting', value: 4 },
  { text: 'Shooter', value: 5 },
  { text: 'Music', value: 7 },
  { text: 'Platform', value: 8 },
  { text: 'Puzzle', value: 9 },
  { text: 'Racing', value: 10 },
  { text: 'Real Time Strategy (RTS)', value: 11 },
  { text: 'Role-playing (RPG)', value: 12 },
  { text: 'Simulator', value: 13 },
  { text: 'Sport', value: 14 },
  { text: 'Strategy', value: 15 },
  { text: 'Turn-based strategy (TBS)', value: 16 },
  { text: 'Tactical', value: 24 },
  { text: "Hack and slash/Beat 'em up", value: 25 },
  { text: 'Quiz/Trivia', value: 26 },
  { text: 'Pinball', value: 30 },
  { text: 'Adventure', value: 31 },
  { text: 'Indie', value: 32 },
  { text: 'Arcade', value: 33 },
  { text: 'Visual Novel', value: 34 },
  { text: 'Card & Board Game', value: 35 },
  { text: 'MOBA', value: 36 },
]
